In [300]:
import numpy as np
import sys
import matplotlib.pyplot as plt
import scipy.sparse.linalg as la
import scipy.sparse as sparse
import time as tm
import logging

In [301]:
def P_i(i,f,n):
    w = 2 * np.pi * f
    T = 1 / f
    k = np.arange(n) + 1
    dt = T / (2 * n + 1)
    #print("omega:", w , " T:", T, " dt:", dt)
    return np.sum(k * np.sin(i * k * w * dt))

In [302]:
def EAE(f,n):
    retMatrix = np.ones((2 * n + 1, 2 * n + 1), dtype = float)
    for a in np.arange(2 * n + 1):
        for b in np.arange(2 * n + 1):
            retMatrix[a,b] = np.sign(b-a) * Pi(abs(b-a),f,n)
    return (2 / (2 * n + 1)) * retMatrix

In [324]:
def operatorMatrix(nn,k1=-1,k2=0,k3=1):
    n = (2 * nn + 1) ** 2
    mat2 = np.zeros((n,n),float)
    
    eae = (EAE(1,nn))
    print("this is EAE")
    print(eae)
    print()
    
    for a in np.arange(2*nn+1):
        print("\n\n\n")
        print("diagonal #", str(a) , "of EAE")
        print(np.diag(eae,a))
        print("diagonal #", str(-a), "of EAE")
        print(np.diag(eae,-a))
        print("The size of this diagonal should be", ((np.diag(eae,-a).size))*(2*nn+1))
        diagg_up = np.zeros(((np.diag(eae,-a).size))*(2*nn+1))
        diagg_down = np.zeros(((np.diag(eae,-a).size))*(2*nn+1))
        for rc in np.arange(np.diag(eae,-a).size):
            curdiag_up = np.diag(eae,a)
            curdiag_down = np.diag(eae,-a)
            diagg_up[1+2*rc+rc*(2*nn + 1 - 2):1+2*rc+(rc+1)*(2*nn + 1 - 2)] = curdiag_up[rc]
            diagg_down[1+2*rc+rc*(2*nn + 1 - 2):1+2*rc+(rc+1)*(2*nn + 1 - 2)] = curdiag_down[rc]
        np.fill_diagonal(mat2[:,abs(a*(2*nn+1)):], diagg_up)
        np.fill_diagonal(mat2[abs(a*(2*nn+1)):, :], diagg_down)
        print("the upper diagonal elements in position #", a ,"are")
        print(diagg_up)
        print("the lower diagonal elements in position #", a ,"are")
        print(diagg_down)
    
    print("\n\n\nthis is the Operator matrix that we created")
    mm2= np.round(mat2, decimals=2)
    print(mm2)
    np.savetxt('my_array2.txt', mm2, fmt='%.2f')

    return mat2

In [325]:
n=2
operator = operatorMatrix(n)


this is EAE
[[ 0.          0.85065081 -0.52573111  0.52573111 -0.85065081]
 [-0.85065081  0.          0.85065081 -0.52573111  0.52573111]
 [ 0.52573111 -0.85065081  0.          0.85065081 -0.52573111]
 [-0.52573111  0.52573111 -0.85065081  0.          0.85065081]
 [ 0.85065081 -0.52573111  0.52573111 -0.85065081  0.        ]]





diagonal # 0 of EAE
[0. 0. 0. 0. 0.]
diagonal # 0 of EAE
[0. 0. 0. 0. 0.]
The size of this diagonal should be 25
the upper diagonal elements in position # 0 are
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
the lower diagonal elements in position # 0 are
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]




diagonal # 1 of EAE
[0.85065081 0.85065081 0.85065081 0.85065081]
diagonal # -1 of EAE
[-0.85065081 -0.85065081 -0.85065081 -0.85065081]
The size of this diagonal should be 20
the upper diagonal elements in position # 1 are
[0.         0.85065081 0.85065081 0.85065081 0.         0.
 0.85065081 0.8